### ISSUE TITLE
Group mananger must deliver the public key.

### ISSUE THREAD

**Issue by jimsch** [EricssonResearch/Multicast-OSCOAP#1]
The endpoint creates a new Recipient Context upon receiving an incoming message from another endpoint in the group for the first time.  ...  each Recipient Context stores also the public key of the associated other endpoint from which  secure messages are received.

How does the recipient of the message get the asym key in a secure manner so that it knows that this is really the key that belongs to the entity.  Pulling from the message means that impersonation is possible so it must have been delivered from the group manager

**Comment by fpalombini** [comment]
This is considered in section 7.3. In the case of a Group Manager providing public keys upon request, we do specify that this is done using the same secure channel used to carry out the join procedure.
